version: '3'

services:
  backend:
    build: ./
    restart: always
    env_file:
      - .env
    environment:
      PORT: 3000
      MARIADB_HOSTNAME: mysql
      MARIADB_PORT: 3306
      MARIADB_USERNAME: converter
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: converter
      entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
      command: ./converter
    expose:
      - "3000"
      - "6060"
    ports:
      - "3000:3000"
      - "6060:6060"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: converter
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: converter
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    ports:
      - "3002:3306"
    volumes:
      - ./dev/data/mysql:/var/lib/mysql
