package icons

const (
	IssueOpened         = "git_issue_opened"
	IssueClosed         = "git_issue_closed"
	PullRequestOpened   = "git_pull_request"
	PullRequestClosed   = "git_pull_request_closed"
	PullRequestApproved = "white_check_mark"
	PullRequestMerged   = "git_merged"
	Pushed              = "git_push_repo"
	Assignment          = "bust_in_silhouette"
	Edit                = "pencil"
	Retrieved           = "leftwards_arrow_with_hook"
	Tag                 = "git_tag"
	Milestone           = "git_milestone"
	Lock                = "lock"
	Unlock              = "unlock"
	Transfer            = "arrow_right"
	Pin                 = "pushpin"
	Comment             = "comment"
	CheckSuccess        = "git_workflow_success"
	CheckFail           = "git_workflow_fail"
	CheckSkip           = "git_workflow_skip"
	CheckCancel         = "git_workflow_cancel"
)
